###
GET http://localhost:8080/api/warehouses HTTP/1.1

###
POST http://localhost:8080/api/warehouses HTTP/1.1
Content-Type: application/json

{
    "warehouse_name": "test_warehouse",
    "address": "test address",
    "city": "test city",
    "country": "testUSA",
    "contact_name": "test name",
    "contact_position": "testposition",
    "contact_phone": "+1 (646) 123-1234",
    "contact_email": "test@instock.com"
}

###
GET http://localhost:8080/api/inventories HTTP/1.1